/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 13-sty-2026 19:39:59 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Coursedto` CASCADE
;

/* Create Tables */

CREATE TABLE `Coursedto`
(
	`Coursecode` varchar(0) NULL,
	`Courseid` varchar(0) NULL,
	`CoursedtoID` varchar(0) NOT NULL,
	`ScheduledtoID` varchar(0) NULL,
	CONSTRAINT `PK_Coursedto` PRIMARY KEY (`CoursedtoID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Coursedto` 
 ADD CONSTRAINT `FK_Coursedto_Scheduledto`
	FOREIGN KEY (`ScheduledtoID`) REFERENCES `Scheduledto` (`ScheduledtoID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 