///////////////////////////////////////////////////////////
//  CSVGenerationService.cs
//  Implementation of the Class CSVGenerationService
//  Generated by Enterprise Architect
//  Created on:      13-sty-2026 19:50:48
//  Original author: bartlomiej.pawelec
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Sterowanie;
namespace Logika {
	public class CSVGenerationService {

		private char csvSeparator;

		public CSVGenerationService(){

		}

		~CSVGenerationService(){

		}

		/// 
		/// <param name="List<Schedule>"></param>
		public void generateCSV(List List<Schedule>){

		}

	}//end CSVGenerationService

}//end namespace Logika