///////////////////////////////////////////////////////////
//  ExportParametersForm.cs
//  Implementation of the Class ExportParametersForm
//  Generated by Enterprise Architect
//  Created on:      13-sty-2026 19:50:52
//  Original author: bartlomiej.pawelec
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejs {
	public class ExportParametersForm {

		private char courseType;
		private char semester;
		private int yearInput;

		public ExportParametersForm(){

		}

		~ExportParametersForm(){

		}

		public void getFormData(){

		}

		public void reset(){

		}

	}//end ExportParametersForm

}//end namespace Interfejs