///////////////////////////////////////////////////////////
//  ExportHttp.cs
//  Implementation of the Class ExportHttp
//  Generated by Enterprise Architect
//  Created on:      13-sty-2026 19:50:50
//  Original author: bartlomiej.pawelec
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejs {
	public class ExportHttp {

		private char baseUrl;
		private int requestTimeout;

		public ExportHttp(){

		}

		~ExportHttp(){

		}

		public void cancelRequest(){

		}

		public void getExportParameters(){

		}

		public void requestExport(){

		}

	}//end ExportHttp

}//end namespace Interfejs