/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 13-sty-2026 19:39:59 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Exportdto` CASCADE
;

/* Create Tables */

CREATE TABLE `Exportdto`
(
	`State` varchar(0) NULL,
	`ExportdtoID` varchar(0) NOT NULL,
	`ScheduledtoID` varchar(0) NULL,
	CONSTRAINT `PK_Exportdto` PRIMARY KEY (`ExportdtoID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Exportdto` 
 ADD CONSTRAINT `FK_Exportdto_Scheduledto`
	FOREIGN KEY (`ScheduledtoID`) REFERENCES `Scheduledto` (`ScheduledtoID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 