/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 13-sty-2026 19:39:59 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Groupdto` CASCADE
;

/* Create Tables */

CREATE TABLE `Groupdto`
(
	`Groupid` varchar(0) NULL,
	`Semesterid` varchar(0) NULL,
	`GroupdtoID` varchar(0) NOT NULL,
	`ScheduledtoID` varchar(0) NULL,
	CONSTRAINT `PK_Groupdto` PRIMARY KEY (`GroupdtoID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Groupdto` 
 ADD CONSTRAINT `FK_Groupdto_Scheduledto`
	FOREIGN KEY (`ScheduledtoID`) REFERENCES `Scheduledto` (`ScheduledtoID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 