///////////////////////////////////////////////////////////
//  ScheduleExportUI.cs
//  Implementation of the Class ScheduleExportUI
//  Generated by Enterprise Architect
//  Created on:      13-sty-2026 19:50:54
//  Original author: bartlomiej.pawelec
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Interfejs;
namespace Interfejs {
	public class ScheduleExportUI {

		private char errorMessage;
		private int return csvBlob;
		private int selectedDepartment;
		private int selectedSemester;
		private int selectScheadule;
		private char title;
		public Interfejs.ExportHttp m_ExportHttp;

		public ScheduleExportUI(){

		}

		~ScheduleExportUI(){

		}

		public void displayError(){

		}

		public void handleExportClick(){

		}

		public void showExportForm(){

		}

	}//end ScheduleExportUI

}//end namespace Interfejs