/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 13-sty-2026 19:39:59 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Scheduledto` CASCADE
;

/* Create Tables */

CREATE TABLE `Scheduledto`
(
	`Courseid` varchar(0) NULL,
	`Scheduleid` varchar(0) NULL,
	`Selectschedule` varchar(0) NULL,
	`ScheduledtoID` varchar(0) NOT NULL,
	CONSTRAINT `PK_Scheduledto` PRIMARY KEY (`ScheduledtoID` ASC)
)

;

SET FOREIGN_KEY_CHECKS=1
; 