/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 13-sty-2026 19:39:06 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Coursedto` CASCADE
;

DROP TABLE IF EXISTS `Exportdto` CASCADE
;

DROP TABLE IF EXISTS `Groupdto` CASCADE
;

DROP TABLE IF EXISTS `Scheduledto` CASCADE
;

DROP TABLE IF EXISTS `Userdto` CASCADE
;

/* Create Tables */

CREATE TABLE `Coursedto`
(
	`Coursecode` varchar(0) NULL,
	`Courseid` varchar(0) NULL,
	`CoursedtoID` varchar(0) NOT NULL,
	`ScheduledtoID` varchar(0) NULL,
	CONSTRAINT `PK_Coursedto` PRIMARY KEY (`CoursedtoID` ASC)
)

;

CREATE TABLE `Exportdto`
(
	`State` varchar(0) NULL,
	`ExportdtoID` varchar(0) NOT NULL,
	`ScheduledtoID` varchar(0) NULL,
	CONSTRAINT `PK_Exportdto` PRIMARY KEY (`ExportdtoID` ASC)
)

;

CREATE TABLE `Groupdto`
(
	`Groupid` varchar(0) NULL,
	`Semesterid` varchar(0) NULL,
	`GroupdtoID` varchar(0) NOT NULL,
	`ScheduledtoID` varchar(0) NULL,
	CONSTRAINT `PK_Groupdto` PRIMARY KEY (`GroupdtoID` ASC)
)

;

CREATE TABLE `Scheduledto`
(
	`Courseid` varchar(0) NULL,
	`Scheduleid` varchar(0) NULL,
	`Selectschedule` varchar(0) NULL,
	`ScheduledtoID` varchar(0) NOT NULL,
	CONSTRAINT `PK_Scheduledto` PRIMARY KEY (`ScheduledtoID` ASC)
)

;

CREATE TABLE `Userdto`
(
	`Email` varchar(0) NULL,
	`Passwordhash` varchar(0) NULL,
	`Userid` varchar(0) NULL,
	`UserdtoID` varchar(0) NOT NULL,
	`GroupdtoID` varchar(0) NULL,
	CONSTRAINT `PK_Userdto` PRIMARY KEY (`UserdtoID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Coursedto` 
 ADD CONSTRAINT `FK_Coursedto_Scheduledto`
	FOREIGN KEY (`ScheduledtoID`) REFERENCES `Scheduledto` (`ScheduledtoID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Exportdto` 
 ADD CONSTRAINT `FK_Exportdto_Scheduledto`
	FOREIGN KEY (`ScheduledtoID`) REFERENCES `Scheduledto` (`ScheduledtoID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Groupdto` 
 ADD CONSTRAINT `FK_Groupdto_Scheduledto`
	FOREIGN KEY (`ScheduledtoID`) REFERENCES `Scheduledto` (`ScheduledtoID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Userdto` 
 ADD CONSTRAINT `FK_Userdto_Groupdto`
	FOREIGN KEY (`GroupdtoID`) REFERENCES `Groupdto` (`GroupdtoID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 
