/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 13-sty-2026 19:39:59 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Userdto` CASCADE
;

/* Create Tables */

CREATE TABLE `Userdto`
(
	`Email` varchar(0) NULL,
	`Passwordhash` varchar(0) NULL,
	`Userid` varchar(0) NULL,
	`UserdtoID` varchar(0) NOT NULL,
	`GroupdtoID` varchar(0) NULL,
	CONSTRAINT `PK_Userdto` PRIMARY KEY (`UserdtoID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Userdto` 
 ADD CONSTRAINT `FK_Userdto_Groupdto`
	FOREIGN KEY (`GroupdtoID`) REFERENCES `Groupdto` (`GroupdtoID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 