#######################################################
# 
# ScheduleBuilder.py
# Python implementation of the Class ScheduleBuilder
# Generated by Enterprise Architect
# Created on:      07-sty-2026 22:26:55
# Original author: bartlomiej.pawelec
# 
#######################################################


class ScheduleBuilder:
    pass